#!/usr/bin/env python
import sys

lookupTable = {
	#Brainfuck chars
	">":"fuck ",
	"<":"fuckers ",
	"+":"fuckity ",
	"-":"fucking ",
	".":"fucked ",
	",":"fuckable ",
	"[":"fuckster ",
	"]":"fuckups ",

	#Special chars
	"\n":"\n",
	"\t":"\t",
	" ":" ",
}

if __name__ == '__main__':
	brainfile = sys.argv[1]
	fuckfile = sys.argv[2]

	b = open(brainfile, 'r')
	f = open(fuckfile, 'w')

	brainsoure = b.read()

	for char in brainsoure:
		try:
			f.write(lookupTable[char])
		except:
			pass
			
	b.close()
	f.close()

