#!/usr/bin/env python
import sys

lookupTable = {
	#Brainfuck chars
	">":"f uck ",
	"<":"ff uck ",
	"+":"fff uck ",
	"-":"ffff uck ",
	".":"fffff uck ",
	",":"ffffff uck ",
	"[":"fffffff uck ",
	"]":"ffffffff uck ",

	#Special chars
	"\n":"\n",
	"\t":"\t",
	" ":" ",
}

if __name__ == '__main__':
	brainfile = sys.argv[1]
	fuckfile = sys.argv[2]

	b = open(brainfile, 'r')
	f = open(fuckfile, 'w')

	brainsoure = b.read()

	for char in brainsoure:
		try:
			f.write(lookupTable[char])
		except:
			pass
			
	b.close()
	f.close()

