#!/usr/bin/env python
import sys
from fuckfuck.parser import FFParser
from fuckfuck.interpreter import FFInterpreter

if __name__ == '__main__':
    p = FFParser.from_file(sys.argv[1])
    t = p.get_tokens()

    i = FFInterpreter()
    i.execute(t)

    print
